language: cpp
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
script:
        mkdir build && cd build && cmake .. && cmake --build . && ctest -V
